import { validateType } from "./index";

// Most tests are autogenerated in top-level tests folder

describe("Setup errors", () => {
  test("No params", () => {
    expect(() => validateType<string>(1)).toThrowError(
      "ts-validate-type requires a build step such as babel-plugin-ts-validate-type"
    );
  });
});
