import * as babel from "@babel/core";
import plugin from ".";

// Most tests are autogenerated in top-level tests folder

describe("Incorrect usage", () => {
  test("No type params", () => {
    const code = `validateType("hello")`;

    expect(() =>
      babel.transform(code, {
        plugins: [plugin],
        filename: "test.ts",
      })
    ).toThrowError("Expected exactly one type parameter");
  });
});
