import * as babel from "@babel/core";
import plugin from ".";

// Most tests are autogenerated in top-level tests folder

function transform(code: string) {
  babel.transform(code, {
    plugins: [plugin],
    filename: "test.ts",
  });
}

describe("Incorrect usage", () => {
  test("No type params", () => {
    expect(() => transform(`validateType("hello")`)).toThrowError(
      "Expected exactly one type parameter"
    );
  });

  test("Type variables", () => {
    expect(() => transform(`validateType<MyType>("hello")`)).toThrowError(
      "validate-ts only supports inline types"
    );
  });

  test("Record number keys", () => {
    expect(() =>
      transform(`validateType<{ 1: string }>({ 1: "hello" })`)
    ).toThrowError("Keys must be string literals");
  });
});
