// This file copies tests from index.ts and transforms them via babel

import * as fs from "fs";
import * as path from "path";
import * as babel from "@babel/core";
import plugin from "../packages/babel-plugin-validate-ts";

/* Generate Babel plugin tests */

const baseTest = path.join(__dirname, "./tests.ts");
const autoGeneratedTest = path.join(__dirname, "./autogenerated.test.ts");

const out = babel.transformFileSync(baseTest, {
  plugins: [plugin],
});

// eslint-disable-next-line @typescript-eslint/no-non-null-assertion
fs.writeFileSync(autoGeneratedTest, out!.code!);
