import { validateType } from "./index";

// Most tests are autogenerated in top-level tests folder

describe("Setup errors", () => {
  test("No params", () => {
    expect(() => validateType<string>(1)).toThrowError(
      "validate-ts requires a build step such as babel-plugin-validate-ts"
    );
  });
});
