import { validateType } from ".";
import { typeVersion } from "../../common/validate-ts-type";

// Most tests are autogenerated in top-level tests folder

describe("Setup errors", () => {
  test("No params", () => {
    expect(() => validateType<string>(1)).toThrowError(
      "validate-ts requires a build step such as babel-plugin-validate-ts"
    );
  });

  test("Version is higher than expected", () => {
    expect(() =>
      validateType<string>(
        1,
        JSON.stringify({ tag: "primitive", type: "string" }),
        typeVersion + 1
      )
    ).toThrowError("Please update validate-ts to the latest version");
  });

  test("Version is lower than expected", () => {
    expect(() =>
      validateType<string>(
        1,
        JSON.stringify({ tag: "primitive", type: "string" }),
        typeVersion - 1
      )
    ).toThrowError(
      "Please update the build step package for validate-ts to the latest version"
    );
  });
});
